dicionario_cuestionario_conceptos = {
    "DDS17_01": "Agotamiento general",
    "DDS17_02": "Desconocimiento del profesional",
    "DDS17_03": "Salud mental",
    "DDS17_04": "Falta de recomendaciones",
    "DDS17_05": "Análisis sangre",
    "DDS17_06": "Rutina diabetes",
    "DDS17_07": "Relaciones interpersonales",
    "DDS17_08": "Control de vida",
    "DDS17_09": "Preocupaciones profesionales",
    "DDS17_10": "Autoconfianza manejo enfermedad",
    "DDS17_11": "Complicaciones largo plazo",
    "DDS17_12": "Falta mantenimiento régimen",
    "DDS17_13": "Relaciones interpersonales",
    "DDS17_14": "Abrumado",
    "DDS17_15": "Preocupaciones profesionales",
    "DDS17_16": "Falta de motivación",
    "DDS17_17": "Apoyo emocional circulo",
    "DIDP_1": "Salud física",
    "DIDP_2": "Situación económica",
    "DIDP_3": "Relaciones interpersonales",
    "DIDP_4": "Actividades de ocio",
    "DIDP_5": "Trabajo/estudios",
    "DIDP_6": "Bienestar emocional"
}
